title: "簡単！Airtestで作るUIテスト"
summary: "UIテストライブラリAirtestを使ったUIテストの作り方とJenkinsへの組み込み"
topics: ["Airtest", "テスト", "Jenkins"]
published: false
price: 300 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - はじめに
  - Airtest
